// Built-in content, ported from reference/index.html (v4.0).
// Shown whenever Airtable has no Published records for a series
// (or the API is unreachable). Shapes match lib/airtable.js output.

export const FALLBACK_SHIFT_FEED = [
  {
    id: 'fb-shift-summer',
    type: 'shift',
    era: 'The Expansion Era',
    season: 'Summer 2026',
    title: 'You Are Allowed to Expand & Stay Soft',
    subtitle: 'Moving Through Summer Unrushed',
    body: 'The expansion era does not require a harder version of you. It requires a more open one. Summer has a way of slowing things down whether you plan for it or not. The light lasts longer. The pace softens. There is permission in the air that does not exist in January.\n\nThis season’s shift is about stepping into your expansion without abandoning your softness. Not shrinking the vision. Not stalling the growth. Just making sure that as you rise, you bring the whole woman with you, including the part that requires rest, joy, and presence to function at her best.',
    quote: 'You do not have to earn this season. You already did.',
    letGoOf: [
      'Urgency dressed up as ambition',
      'Performing productivity for an audience',
      'Rushing through a season meant for receiving',
      'The belief that softness and success cannot coexist',
    ],
    inviteIn: [
      'Expansion that feels like yourself',
      'Growth that leaves room for joy',
      'Summer mornings with no agenda',
      'Pride in how far you have already come',
    ],
    journalingPrompt: 'What does an open, unhurried summer look like for me? What am I finally ready to receive?',
    tip: 'Bloom where you are planted, then expand where the sun finds you.',
    isNew: true,
  },
  {
    id: 'fb-note-1',
    type: 'note',
    body: 'Luxury is not impulse. Luxury is intention. Every choice you make with care is an act of self-respect.',
    highlight: 'intention.',
    isNew: false,
  },
  {
    id: 'fb-shift-1',
    type: 'shift',
    era: 'The Becoming Era',
    season: 'Spring 2026',
    title: 'You Are Allowed to Grow & Stay Soft',
    subtitle: 'Moving Through Life Unrushed',
    body: "Growth does not require you to become harder. You can grow peacefully. You can expand intentionally. This season's shift is about protecting your softness as you bloom, not shrinking, not stopping, just making sure that as you grow, you bring the whole woman with you.",
    quote: 'You are not behind. You are right on time for the life you are actually building.',
    letGoOf: [
      "Growing at someone else's pace",
      'Performing progress for approval',
      'Hustling through seasons meant for rest',
      'Apologizing for choosing yourself',
    ],
    inviteIn: [
      'Growth that feels like yourself',
      'Expansion rooted in intention',
      'Seasons of both bloom and rest',
      'Pride in the quiet progress',
    ],
    tip: 'The soft life is not a destination. It is the way you travel.',
    journalingPrompt: '',
    isNew: false,
  },
  {
    id: 'fb-note-2',
    type: 'note',
    body: "You handled this season with more calm than you're giving yourself credit for. That is the work.",
    highlight: 'more calm',
    isNew: false,
  },
  {
    id: 'fb-shift-2',
    type: 'shift',
    era: 'The Reset Era',
    season: 'January 2026',
    title: 'Gentle Goals Framework',
    subtitle: 'Where Intention Meets Ease',
    body: "January doesn't require a complete overhaul. It asks for clarity. The Soft Life Shift invites you to release pressure-driven goals and replace them with gentle intentions that support how you actually live. This is about creating rhythms you can return to, not routines you abandon by week three.",
    quote: "A soft life isn't unproductive. It's intentional.",
    letGoOf: [
      'All-or-nothing thinking',
      'Overpacked schedules',
      'Comparing your pace to others',
      'Goals rooted in guilt',
    ],
    inviteIn: [
      'Clear priorities',
      'Calm mornings',
      'Intentional spending',
      'Daily moments of beauty',
    ],
    tip: "You don't owe urgency to anyone.",
    journalingPrompt: '',
    isNew: false,
  },
  {
    id: 'fb-note-3',
    type: 'note',
    body: 'Pace does not equal purpose. I thrive in alignment, not urgency.',
    highlight: 'not urgency.',
    isNew: false,
  },
  {
    id: 'fb-shift-3',
    type: 'shift',
    era: 'The Reset Era',
    season: 'Thanksgiving 2025',
    title: 'Gratitude Journaling & Slowing Down',
    subtitle: 'The Quiet Luxury of Gratitude',
    body: "Gratitude as a grounding ritual, not just saying thanks, but noticing beauty in what's already here. By dedicating just a few moments each day to reflect on what you're thankful for, you cultivate a more positive mindset and deeper connection.",
    quote: 'Gratitude turns what we have into enough, and enough into abundance.',
    letGoOf: [],
    inviteIn: [
      'Morning gratitude routine with tea',
      'Handwritten note to someone you love',
      'Screen-free evening by candlelight',
    ],
    inviteHeading: 'Savor the Moment With',
    journalingPrompt: 'List three moments from this week that felt soft.',
    tip: 'Gratitude is the language of soft living.',
    isNew: false,
  },
];

export const FALLBACK_LESSONS = [
  {
    id: 'fb-l7',
    episode: 7,
    epLabel: 'EP. 07 · 2026',
    era: 'The Expansion Era',
    season: 'Summer 2026',
    category: 'Growth',
    title: "Expansion Doesn't Have to Be Loud",
    body: 'There is a version of expansion you have been sold that looks like urgency. Like early mornings and late nights. Like proving your ambition through your exhaustion. That is not the expansion we are talking about here.\n\nThe expansion we are building at Simpli Luxe is quieter. It is steadier. It happens in the margins of a life that already feels good, not after one. You do not force a flower into the sun. You create the conditions. You tend the soil. You protect the roots. And when the season is right, it opens.\n\nSummer is that season for you. Not a season to sprint. A season to open. To receive what the previous seasons prepared you for. You have already done the work. The reset. The becoming. Now it is summer. And you are in full sun.',
    quote: 'Expansion is not something you chase. It is something you grow into, slowly, intentionally, on your own terms.',
    isNew: true,
  },
  {
    id: 'fb-l6',
    episode: 6,
    epLabel: 'EP. 06 · 2026',
    era: 'The Becoming Era',
    season: 'Spring 2026',
    title: 'Growing Without Rushing',
    body: 'There is a difference between growing and rushing. Rushing is chasing the next version of yourself before you have fully inhabited this one. The rooted woman grows without rushing. She blooms without performing.',
    isNew: false,
  },
  {
    id: 'fb-l5',
    episode: 5,
    epLabel: 'EP. 05 · 2026',
    era: 'The Reset Era',
    season: 'Jan 2026',
    title: 'Confidence Without Performance',
    body: "Confidence doesn't arrive loudly. It doesn't announce itself. It settles. The truest confidence comes when you stop needing validation for choices that already feel aligned.",
    isNew: false,
  },
  {
    id: 'fb-l4',
    episode: 4,
    epLabel: 'EP. 04 · 2026',
    era: 'The Reset Era',
    season: 'Jan 2026',
    title: 'Resetting Without Reinventing',
    body: "A new year doesn't require a complete overhaul. This season is an invitation to reset gently, to refocus on what already works, and to radiate from a place of clarity instead of pressure.",
    isNew: false,
  },
  {
    id: 'fb-l3',
    episode: 3,
    epLabel: 'EP. 03 · 2025',
    era: 'The Reset Era',
    season: 'Dec 2025',
    title: 'The Magic of Making Moments Luxe',
    body: "Luxury isn't what you buy, it's how you make the ordinary feel extraordinary. Luxury lives in those in-between moments when you choose presence over perfection.",
    isNew: false,
  },
  {
    id: 'fb-l2',
    episode: 2,
    epLabel: 'EP. 02 · 2025',
    era: 'The Reset Era',
    season: 'Nov 2025',
    title: 'The Quiet Luxury of Gratitude',
    body: "Gratitude as a grounding ritual, not just saying thanks, but noticing beauty in what's already here. Practicing gratitude daily transforms perspective and fosters deeper connection.",
    isNew: false,
  },
  {
    id: 'fb-l1',
    episode: 1,
    epLabel: 'EP. 01 · 2025',
    era: 'The Reset Era',
    season: 'Nov 2025',
    title: 'The Soft Power of Slowing Down',
    body: "Rest doesn't always look like laying down. Sometimes it looks like choosing the gentle option instead of the exhausting one. When life feels loud, returning to your small rituals is the most luxurious thing you can do.",
    isNew: false,
  },
];

export const FALLBACK_SIPS = [
  {
    id: 'fb-s1',
    episode: 1,
    epLabel: 'EP. 01 · NOV 2025',
    title: 'Lavender Lemonade Refresher',
    heroTitle: 'Lavender Lemonade\nRefresher',
    vibe: 'Light. Floral. Grounding.',
    heroClass: 'bglav',
    era: 'The Reset Era',
    eraShort: 'The Reset',
    season: 'Fall 2025',
    flavorTags: ['Light & Floral'],
    modalTag: 'EP. 01 · Nov 2025 · The Reset Era · Fall',
    flavorProfile: 'Light, floral, and gently grounding. A soft start or a Sunday reset, this sip signals intention without effort.',
    ingredients: [
      'Fresh lemon juice',
      'Lavender simple syrup',
      'Sparkling water',
      'Crushed ice',
      'Garnish: lemon slice + lavender sprig',
    ],
    howToMake: [
      'Simmer equal parts sugar and water with dried lavender 10 min, strain, cool to make syrup',
      'Fill glass with crushed ice',
      'Add lemon juice and lavender syrup, stir gently',
      'Top with sparkling water and garnish',
    ],
    ritualMoment: 'Pour this during your Sunday reset. Soft music, 15-minute quiet tidy, this sip in hand. Let it signal the transition from the week behind to the week ahead.',
    vibeNotes: 'Slow down. Sip with intention. This moment is yours.',
    isNew: false,
  },
  {
    id: 'fb-s2',
    episode: 2,
    epLabel: 'EP. 02 · THANKSGIVING 2025',
    title: 'Sunset Muse · Fall Edition',
    heroTitle: 'Sunset Muse\nFall Edition 🍂',
    vibe: 'Citrus. Spice. Autumn sunset in a glass.',
    heroClass: 'bgsun',
    era: 'The Reset Era',
    eraShort: 'The Reset',
    season: 'Thanksgiving',
    flavorTags: ['Warm & Cozy'],
    modalTag: 'EP. 02 · Thanksgiving 2025 · The Reset Era',
    flavorProfile: 'A cozy yet refreshing mix of citrus and spice. The warmth of a Moscow Mule, the brightness of blood orange, and the comfort of classic lemonade. Autumn sunset in a glass.',
    ingredients: [
      '3 oz Summit Moscow Mule Mocktail (zero sugar)',
      '2 oz Pur Aqua Blood Orange Italian Sparkling Beverage',
      "2 oz Member's Mark Lemonade",
      'Fresh strawberry slices',
      'Optional: red sugar or cinnamon-sugar rim',
    ],
    howToMake: [
      'Rim glass with red or cinnamon sugar',
      'Add ice and pour in all three drinks',
      'Stir gently to combine',
      'Garnish with strawberries or dehydrated orange wheel',
    ],
    ritualMoment: 'Serve in a clear glass or copper mug. Add a cinnamon stick stirrer. Set the scene with candlelight and neutral fall textures.',
    vibeNotes: 'Autumn sunset in a glass. Gratitude in every sip.',
    isNew: false,
  },
  {
    id: 'fb-s3',
    episode: 3,
    epLabel: 'EP. 03 · DECEMBER 2025',
    title: 'Merry & Bright Spritz',
    heroTitle: 'Merry & Bright\nSpritz 🌲',
    vibe: 'Cranberry. Vanilla. Festive cheer.',
    heroClass: 'bgcran',
    era: 'The Reset Era',
    eraShort: 'The Reset',
    season: 'Holiday',
    flavorTags: ['Sparkling'],
    modalTag: 'EP. 03 · December 2025 · The Reset Era · Holiday',
    flavorProfile: 'Bright cranberry meets smooth vanilla and a hint of rosemary. Festive, fragrant, and perfect for sipping under twinkle lights.',
    ingredients: [
      '3 oz cranberry juice',
      '2 oz lemon sparkling water or club soda',
      '1 oz vanilla syrup',
      'Fresh rosemary sprig',
      'Garnish: cranberries + sugared rim',
    ],
    howToMake: [
      'Rim glass with sugar and crushed rosemary',
      'Add ice, cranberry juice, and vanilla syrup',
      'Top with sparkling water and stir gently',
      'Garnish with cranberries and rosemary',
    ],
    ritualMoment: 'Serve in a coupe or stemmed glass for a luxe presentation. Slow morning before the holiday rush. This is your moment.',
    vibeNotes: 'Peace is my luxury. Presence is my gift.',
    isNew: false,
  },
  {
    id: 'fb-s4',
    episode: 4,
    epLabel: 'EP. 04 · JAN 2026',
    title: 'The Golden Reset Mocktail',
    heroTitle: 'The Golden\nReset Mocktail',
    vibe: 'Warm. Grounding. Golden hour in a mug.',
    heroClass: 'bggold',
    era: 'The Reset Era',
    eraShort: 'The Reset',
    season: 'Winter 2026',
    flavorTags: ['Warm & Cozy'],
    modalTag: 'EP. 04 · Jan 2026 · The Reset Era · Winter',
    flavorProfile: 'Warm, golden, and deeply calming. Turmeric warmth, honey sweetness, and gentle cinnamon comfort. January in a mug.',
    ingredients: [
      '1 cup warm oat milk or almond milk',
      '1 tsp raw honey or maple syrup',
      '¼ tsp ground turmeric',
      'Pinch of cinnamon',
      'Pinch of ginger (optional)',
      'Dash of vanilla extract',
    ],
    howToMake: [
      'Warm the milk gently. Do not boil',
      'Whisk in honey, turmeric, cinnamon, ginger, vanilla',
      'Pour into your favorite mug',
      'Sip slowly, intentionally',
    ],
    ritualMoment: 'Light a candle, turn on soft music, drink this without distractions. Let it signal the end of your day or the beginning of a calm morning.',
    vibeNotes: 'Rest can be ritual. Slowing down can be intentional.',
    isNew: false,
  },
  {
    id: 'fb-s5',
    episode: 5,
    epLabel: 'EP. 05 · JAN 2026',
    title: 'The Steady Glow Mocktail',
    heroTitle: 'The Steady\nGlow Mocktail',
    vibe: 'Citrus. Honey. Settle, not shut down.',
    heroClass: 'bggold2',
    era: 'The Reset Era',
    eraShort: 'The Reset',
    season: 'Winter 2026',
    flavorTags: ['Light & Fresh'],
    modalTag: 'EP. 05 · Jan 2026 · The Reset Era · Winter',
    flavorProfile: 'A grounding sip for evenings when you want to settle, not shut down. Simple ingredients, quiet luxury.',
    ingredients: [
      'Sparkling water or warm herbal tea',
      'Fresh citrus (orange or lemon)',
      'Honey or maple syrup',
      'Fresh rosemary or ginger',
    ],
    howToMake: [
      'Pour slowly',
      'Sip without distractions',
      'Let this moment signal steadiness',
    ],
    stepsHeading: 'Serving Ritual',
    ritualMoment: 'This is the sip you reach for at the end of the day. Not to shut down, but to settle in. Pour slowly. Breathe. Let this moment be yours.',
    vibeNotes: "Confidence doesn't rush.",
    isNew: false,
  },
  {
    id: 'fb-s6',
    episode: 6,
    epLabel: 'EP. 06 · SPRING 2026',
    title: 'My Spring Reset Mocktail Ritual',
    heroTitle: 'My Spring Reset\nMocktail Ritual',
    vibe: 'Fresh. Floral. Complete reset.',
    heroClass: 'bgspr',
    era: 'The Becoming Era',
    eraShort: 'The Becoming',
    season: 'Spring 2026',
    flavorTags: ['Light & Floral'],
    modalTag: 'EP. 06 · Spring 2026 · The Becoming Era',
    flavorProfile: 'Fresh. Floral. Refreshing. Light cucumber meets bright lemon and elderflower. A complete afternoon reset in 5 minutes.',
    ingredients: [
      '1 cup sparkling water',
      '2 oz elderflower tonic (Fever-Tree)',
      '3–4 slices cucumber',
      'Fresh mint leaves',
      '½ lemon, squeezed',
      'Ice + optional garnish',
    ],
    howToMake: [
      'Fill glass with ice',
      'Add cucumber slices and fresh mint',
      'Squeeze in lemon juice',
      'Pour in elderflower tonic',
      'Top with sparkling water, stir gently, garnish',
    ],
    ritualHeading: 'Ritual Moment · 5 Minutes Complete Reset',
    ritualMoment: 'Sip this when you need a soft pause. Step outside. Breathe. Reset your mind, your mood, and your energy. Make it sacred.',
    vibeNotes: "Luxury doesn't have to be expensive. Sometimes it's five minutes and a beautiful glass.",
    isNew: false,
  },
];

// The Simpli Edit issue covers (Vol 01–06), rendered as designed
// gradient tiles when no Attachment cover exists.
export const FALLBACK_EDIT_ISSUES = [
  {
    id: 'fb-e7',
    volume: 7,
    volLabel: 'Vol 07 · Summer 2026',
    miniLabel: 'Vol 07 · Summer 2026',
    title: 'Full Sun. Expanding. Fully Hers.',
    coverLines: [
      { text: 'Full Sun.', color: 'var(--ww)' },
      { text: 'Expanding.', color: 'var(--gold-l)' },
      { text: 'Fully Hers.', color: 'var(--gold)', italic: true },
    ],
    script: '+ The In Full Sun Edit',
    gradient: 'linear-gradient(155deg,#1c1408,#42300c 45%,#1c1408)',
    season: 'Summer 2026',
    seasonClass: 'bsum',
    eraShort: 'The Expansion',
    isNew: true,
  },
  {
    id: 'fb-e6',
    volume: 6,
    volLabel: 'Vol 06 · Spring 2026',
    miniLabel: 'Vol 06 · Spring 2026',
    title: 'Rooted. Blooming. Fully Hers.',
    coverLines: [
      { text: 'Rooted.', color: 'var(--ww)' },
      { text: 'Blooming.', color: '#7a9e72' },
      { text: 'Fully Hers.', color: 'var(--gold)', italic: true },
    ],
    script: '+ Rooted & Blooming',
    gradient: 'linear-gradient(155deg,#0f1610,#151e12 50%,#0f1610)',
    season: 'Spring 2026',
    seasonClass: 'bspr',
    eraShort: 'The Becoming',
    isNew: false,
  },
  {
    id: 'fb-e5',
    volume: 5,
    volLabel: 'Vol 05 · Jan 2026',
    miniLabel: 'Vol 05 · Confidence',
    title: 'Quiet Confidence. Cultivated.',
    coverLines: [
      { text: 'Quiet', color: 'var(--ww)' },
      { text: 'Confidence.', color: 'var(--ww)' },
      { text: 'Cultivated.', color: 'var(--gold)' },
    ],
    script: '+ Quiet Confidence Edit',
    gradient: 'linear-gradient(155deg,#16120c,#22180e 50%,#16120c)',
    season: 'Jan 2026',
    seasonClass: 'bwin',
    eraShort: 'The Reset',
    isNew: false,
  },
  {
    id: 'fb-e4',
    volume: 4,
    volLabel: 'Vol 04 · New Year 2026',
    miniLabel: 'Vol 04 · New Year',
    title: 'Reset. Refocus. Radiate.',
    coverLines: [
      { text: 'Reset.', color: 'var(--ww)' },
      { text: 'Refocus.', color: 'var(--ww)' },
      { text: 'Radiate.', color: 'var(--gold)' },
    ],
    script: '+ The New Year Edit',
    gradient: 'linear-gradient(155deg,#1a1108,#2C1810 40%,#1a1108)',
    season: 'Winter 2026',
    seasonClass: 'bwin',
    eraShort: 'The Reset',
    isNew: false,
  },
  {
    id: 'fb-e3',
    volume: 3,
    volLabel: 'Vol 03 · Dec 2025',
    miniLabel: 'Vol 03 · Holiday',
    title: 'Holiday Glam, Simplified.',
    coverLines: [
      { text: 'Holiday Glam,', color: 'var(--ww)' },
      { text: 'Simplified.', color: 'var(--gold)', italic: true },
    ],
    script: '+ The Holiday Edit',
    gradient: 'linear-gradient(155deg,#0d1010,#1a2015 50%,#0d1010)',
    season: 'December 2025',
    seasonClass: 'bhol',
    eraShort: 'The Reset',
    isNew: false,
  },
  {
    id: 'fb-e2',
    volume: 2,
    volLabel: 'Vol 02 · Thanksgiving 2025',
    miniLabel: 'Vol 02 · Gratitude',
    title: 'Your Holiday Luxe Formula',
    coverLines: [
      { text: 'Your Holiday', color: 'var(--ww)' },
      { text: 'Luxe Formula', color: 'var(--gold)' },
    ],
    script: '+ Gratitude Issue',
    gradient: 'linear-gradient(155deg,#12100a,#2a2010 50%,#12100a)',
    season: 'Thanksgiving',
    seasonClass: 'bhol',
    eraShort: 'The Reset',
    isNew: false,
  },
  {
    id: 'fb-e1',
    volume: 1,
    volLabel: 'Vol 01 · Nov 2025',
    miniLabel: 'Vol 01 · Debut',
    title: 'Soft Life, Styled.',
    coverLines: [
      { text: 'Soft Life,', color: 'var(--ww)' },
      { text: 'Styled.', color: 'var(--gold)', italic: true },
    ],
    script: 'Weekly Luxe Lifestyle',
    gradient: 'linear-gradient(155deg,#1a0e08,#3d1e0a 40%,#1a0e08)',
    season: 'Fall 2025',
    seasonClass: 'bfall',
    eraShort: 'The Reset',
    isNew: false,
  },
];

export const FALLBACK_STYLED = [
  {
    id: 'fb-b0',
    name: 'The Soft Summer Capsule',
    tagline: 'Dress for the life you are already living',
    tag: 'Summer · The Expansion Era',
    lookCount: '4 Looks',
    boardClass: 'bsun',
    palette: ['#FDFAF5', '#E8DCC8', '#C19A6B', '#C9A96E'],
    seasonTag: 'Summer 2026',
    seasonClass: 'bsum',
    eraShort: 'The Expansion',
    isNew: true,
  },
  {
    id: 'fb-b1',
    name: 'Simpli Luxe Signature Capsule',
    tagline: 'Intentional · Feminine · Luxe-for-Less',
    tag: 'Year-Round',
    lookCount: '10 Looks',
    boardClass: 'bsig',
    palette: ['#F5F0E8', '#C9A96E', '#8C7B6B', '#2C1810', '#722F37'],
    isNew: false,
  },
  {
    id: 'fb-b2',
    name: 'Spring / Summer Capsule',
    tagline: 'Soft · Elegant · Resort Inspired',
    tag: 'Spring · Summer',
    lookCount: '10 Looks',
    boardClass: 'bss',
    palette: ['#FDFAF5', '#F5DEB3', '#FFB6C1', '#8FBC8F'],
    seasonTag: 'Spring 2026',
    seasonClass: 'bspr',
    eraShort: 'The Becoming',
    isNew: false,
  },
  {
    id: 'fb-b3',
    name: 'Fall / Winter Capsule',
    tagline: 'Refined Romantic Executive',
    tag: 'Fall · Winter',
    lookCount: '10 Looks',
    boardClass: 'bfw',
    palette: ['#C19A6B', '#3C1F0F', '#556B2F', '#722F37'],
    seasonTag: 'Fall/Winter',
    seasonClass: 'bfall',
    isNew: false,
  },
  {
    id: 'fb-b4',
    name: 'Simpli Luxe Travel Capsule',
    tagline: 'Pack Less · Look Better · Live Fully',
    tag: 'Travel · Jet Set',
    lookCount: '10 Looks',
    boardClass: 'btrv',
    palette: ['#FDFAF5', '#C19A6B', '#556B2F', '#4682B4'],
    isNew: false,
  },
];

export const FALLBACK_COLLECTIONS = [
  {
    id: 'fb-c1',
    name: 'Becoming Era Summer Capsule',
    heroTitle: '☀️ Becoming Era\nSummer Capsule',
    tag: 'The Becoming Era · Summer 2026',
    filterTags: ['Style'],
    description: 'Summer dressing should feel like relief. A handful of beautiful pieces that do everything.',
    heroClass: 'cbg1',
    featured: true,
    featuredDescription: 'Summer dressing should feel like relief. Not more decisions, not more trends. Just beautiful pieces that work together effortlessly.',
    shopMyLink: '',
  },
  {
    id: 'fb-c2',
    name: 'Soft Life Maintenance Kit',
    heroTitle: 'Soft Life\nMaintenance Kit',
    tag: 'Lifestyle · Ritual',
    filterTags: ['Lifestyle'],
    description: "The soft life isn't built in one perfect weekend reset. It's maintained in the small rituals that bring you back to yourself.",
    heroClass: 'cbg6',
    featured: false,
    shopMyLink: '',
  },
  {
    id: 'fb-c3',
    name: '5 Pieces, Endless Outfits',
    heroTitle: '5 Pieces,\nEndless Outfits',
    tag: 'Capsule · Wardrobe Essentials',
    filterTags: ['Style'],
    description: '5 staples that maintain your style without stress. Pieces that mix effortlessly and always look intentional.',
    heroClass: 'cbg5',
    featured: false,
    shopMyLink: '',
  },
  {
    id: 'fb-c4',
    name: 'Simpli Luxe Tailored Edit',
    heroTitle: 'Tailored Edit:\nBecoming Era',
    tag: 'Workwear · The Becoming Era',
    filterTags: ['Style'],
    description: 'Structured blazers, cinched waistcoats, and tailored trousers that look expensive and feel powerful.',
    heroClass: 'cbg1',
    featured: true,
    featuredTag: 'The Becoming Era · Workwear',
    featuredName: 'Tailored Edit: Becoming Era',
    featuredDescription: 'Tailored pieces that look expensive, feel powerful, and move like intention. Structured blazers, cinched waistcoats, and tailored trousers.',
    shopMyLink: '',
  },
  {
    id: 'fb-c5',
    name: 'Simpli Luxe Mocktail Essentials',
    heroTitle: 'Mocktail\nEssentials',
    tag: 'Lifestyle · The Simpli Sip',
    filterTags: ['Lifestyle', 'Mocktail'],
    description: 'Everything you need to create elevated, alcohol-free drinks at home. Glassware, premium mixers, and finishing touches.',
    heroClass: 'cbg3',
    featured: false,
    shopMyLink: '',
  },
  {
    id: 'fb-c6',
    name: 'Simpli Luxe Intentional Splurges',
    heroTitle: 'Intentional\nSplurges',
    tag: 'Investment Pieces · 49 Products',
    filterTags: ['Investment'],
    description: 'Investment pieces that elevate your wardrobe and lifestyle long-term. The items you buy once and style for years.',
    heroClass: 'cbg8',
    featured: false,
    shopMyLink: '',
  },
  {
    id: 'fb-c7',
    name: 'Small Luxuries (Under $30)',
    heroTitle: 'Small Luxuries\nUnder $30',
    tag: 'Budget Luxe · Everyday',
    filterTags: ['Budget Luxe'],
    description: 'Small upgrades that quietly change your day. Softer mornings, calmer spaces, a more intentional life.',
    heroClass: 'cbg7',
    featured: true,
    featuredTag: 'Everyday · Budget Luxe',
    featuredName: 'Simpli Luxe Small Luxuries',
    featuredDescription: 'Small luxuries that elevate your everyday routines without overspending. Softer mornings, calmer spaces, more intentional life.',
    shopMyLink: '',
  },
  {
    id: 'fb-c8',
    name: 'Simpli Luxe Spring Wardrobe',
    heroTitle: 'Spring Wardrobe\nUnder $75',
    tag: 'Spring 2026 · 37 Products',
    filterTags: ['Style', 'Budget Luxe'],
    description: 'A curated spring wardrobe built on elevated basics that look expensive, feel effortless, and work together seamlessly.',
    heroClass: 'cbg2',
    featured: false,
    shopMyLink: '',
  },
];

// The five moment categories shown on the homepage teaser. Kept as a
// fixed list (not derived from live records) so every category has a
// filter tab on /luxuries even before Staci has published a moment in
// it yet, e.g. Out & About for travel content.
export const LUXURY_CATEGORIES = [
  'Love & Relationships',
  'Soft Evenings',
  'Everyday Indulgence',
  'Out & About',
  'Personal Joy',
];

export const FALLBACK_LUXURIES = [
  {
    id: 'fb-lux-1',
    title: 'A Perfectly Made Coffee',
    body: 'Slow mornings start with a cup made just for you. No rushing the pour, no drinking it lukewarm at your desk. Five quiet minutes, entirely yours.',
    category: 'Soft Evenings',
    media: [],
    isNew: true,
  },
  {
    id: 'fb-lux-2',
    title: 'Morning Light Through Clean Windows',
    body: 'There is a version of luxury that costs nothing at all. Clean windows, a made bed, light pouring in exactly where you left space for it.',
    category: 'Everyday Indulgence',
    media: [],
    isNew: false,
  },
  {
    id: 'fb-lux-3',
    title: 'The Joy of a Fresh Candle',
    body: 'A new candle on a quiet evening. Small, deliberate, entirely for you. The soft life lives in moments exactly like this one.',
    category: 'Personal Joy',
    media: [],
    isNew: false,
  },
  {
    id: 'fb-lux-4',
    title: 'A Long Overdue Coffee Date',
    body: 'Choosing presence over busyness. Sitting across from someone you love with nowhere else to be, for once.',
    category: 'Love & Relationships',
    media: [],
    isNew: false,
  },
  {
    id: 'fb-lux-5',
    title: 'A Weekend Away, Unplanned Past Sunset',
    body: 'A new city, a slow morning, nowhere you have to be by a certain time. The best trips leave room for the moments you did not plan.',
    category: 'Out & About',
    media: [],
    isNew: false,
  },
];

// The five recurring Insider Weekly pillars, matching the AI content
// engine's own vocabulary (Content Queue's Destination Table values).
export const INSIDER_PILLARS = [
  'Daily Affirmation',
  'Sunday Reset',
  'Money Monday',
  'Wellness Wednesday',
  'Weekend Luxury Guide',
];

export const FALLBACK_INSIDER_WEEKLY = [
  {
    id: 'fb-ins-1',
    title: 'Room to Expand',
    pillar: 'Daily Affirmation',
    quote: 'I am allowed to grow into the fullness of who I am becoming, without apology and without rushing.',
    body: "There's a version of you that's been quietly outgrowing spaces she used to shrink herself to fit. Sit with that. The expansion happening in you right now is not loud. It's a Tuesday afternoon decision. A boundary held gently but firmly.\n\nJournal Question: Where have you been taking up more space lately, even in small ways, and what has that felt like in your body?",
    premium: true,
    isNew: true,
  },
  {
    id: 'fb-ins-2',
    title: 'Spend Like You Mean It',
    pillar: 'Money Monday',
    body: 'Every dollar is a vote for the life you are building. Before you spend this week, ask: does this purchase move me toward the woman I am becoming, or is it just a habit? A budget that breathes still has a spine.',
    premium: true,
    isNew: false,
  },
  {
    id: 'fb-ins-3',
    title: 'The Tuesday Afternoon Reset',
    pillar: 'Wellness Wednesday',
    body: 'Wellness does not require an hour you do not have. Three slow breaths before you open your next email. A glass of water before the coffee. A short walk between calls. Small resets, repeated, are the whole practice.',
    premium: false,
    isNew: false,
  },
  {
    id: 'fb-ins-4',
    title: 'This Weekend, You Are Not Behind',
    pillar: 'Weekend Luxury Guide',
    body: 'A slow Saturday morning. A single errand instead of five. One beautiful meal, cooked unhurried. This is not laziness, it is recovery. You do not owe this weekend a project.',
    premium: true,
    isNew: false,
  },
  {
    id: 'fb-ins-5',
    title: 'You Showed Up. That Was Enough.',
    pillar: 'Sunday Reset',
    body: 'Before the new week begins, take stock softly. What worked. What you want to release. What you are ready to invite in. Light a candle if that helps. Write three lines if that helps. There is no wrong way to close a week gently.',
    premium: false,
    isNew: false,
  },
];

export const HERO_QUOTES = [
  '"Luxury is choosing the pace that honors you."',
  '"A soft life isn\'t unproductive. It\'s intentional."',
  '"Confidence is being rooted enough to remain calm."',
  '"You\'re not too much. You\'re exactly enough."',
  '"Peace feels different now. Quieter. Softer. Real."',
  '"Luxury is intention in motion, every single day."',
  '"She was always going to bloom."',
  '"The rooted woman grows without rushing."',
];
